baseURL = "https://lun15.github.io/"
title = "Skeleton-Based Graph Convolutional Networks for Human Action Detailed Description"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Skeleton-Based Graph Convolutional Networks for Human Action Detailed Description" # title for frontpage, may include image
copyright = "John Doe"
description = '葉惟欣 F74109016<br />黃佳倫 E64096245<br />黃翊瑄 AN4096019'
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"


[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Abstract'
body = '''
The relationship between vision and languages is important in our daily life. There are many researches concerning making computers to describe human actions such like Video Captioning, text to image or video. When it comes to human motion, there are fewer researches. The Task “Motion to description” is difficult, not to mention the task “Motion to detailed descriptions such as body parts”. Also, those researches about motion analysis mostly based on the joints connected with skeletons.

However, we think that the relationships between the disconnected joints are also important to motion analysis. Furthermore, movement of one part of the body that leads to a change in the overall posture, such as kicking with a leg to transition the entire body into an attacking stance. In order to consider such motion, the skeleton graph will need to consider the relationship between joints in different time.
</a>'''



[params.two]
enable = true

[[params.two.section]]
img = "img/example.gif"
img_alt = "blurry background: white/grey"
title = '3D movement'
body = '''
For our downstream task ”extract meaningful information of human pose by skeleton graph”, we reconstruct the world of 3D skeleton by the SMPL format of human pose.

We use ”Decoupling Human and Camera Motion from Videos in the Wild” to first extract accurate 3D world joints. They infer 3D human motion with a full scene reconstruction for in-the-wild-videos.
'''

[[params.two.section]]
img = "img/skeleton.png"
alt = "blurry background: grey/white"
#title = 'Tortor dolore feugiat<br />elementum magna'
title = '2D Graphs'
body = '''
The initial connections in the 2-dimensional graph generated by OpenPose, which includes only 18 joints, do not adequately account for expanded connections between non-adjacent joints. 

Consequently, we manually add connections between the shoulders and the hips of the skeleton. This addition aims to improve the accuracy of link prediction as these joints may exhibit direct relationships during movement.
'''

[[params.two.section]]
img = "img/skeleton.jpg"
title = 'Magna primis lobortis<br />sed ullamcorper'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec hendrerit imperdiet. Mauris eleifend fringilla nullam aenean mi ligula.'

[params.three]
enable = true
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Title"
body = "."

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"
